name: flutter_multi_vendor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  country_picker: ^2.0.24
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  flutter_hooks: ^0.20.5
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  glass: ^2.0.0+1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  lottie: ^3.0.0
  otp_text_field: ^1.1.3
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.12.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/anime/
   - assets/icons/
